### ISSUE TITLE
[rank0]: RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by YerongLi** [cientgu/InstructDiffusion#22]
```
CUDA_VISIBLE_DEVICES=2 python -m torch.distributed.launch --nproc_per_node=1 main.py --name v0 --base configs/instruct_diffusion.yaml --train --logdir logs/instruct_diffusion
```
I met this error **"[rank0]: RuntimeError: expected scalar type Half but found Float"**

```
[rank0]:   File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
[rank0]:     ret_val = func(*args, **kwargs)
[rank0]:   File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1846, in forward
[rank0]:     loss = self.module(*inputs, **kwargs)
[rank0]:   File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "./stable_diffusion/ldm/models/diffusion/ddpm_edit.py", line 778, in forward
[rank0]:     x, c = self.get_input(batch, self.first_stage_key)
[rank0]:   File "./stable_diffusion/ldm/models/diffusion/ddpm_edit.py", line 605, in get_input
[rank0]:     null_prompt = self.get_learned_conditioning([""])
[rank0]:   File "./stable_diffusion/ldm/models/diffusion/ddpm_edit.py", line 487, in get_learned_conditioning
[rank0]:     c = self.cond_stage_model.encode(c)
[rank0]:   File "./stable_diffusion/ldm/modules/encoders/modules.py", line 162, in encode
[rank0]:     return self(text)
[rank0]:   File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "./stable_diffusion/ldm/modules/encoders/modules.py", line 156, in forward
[rank0]:     outputs = self.transformer(input_ids=tokens)
[rank0]:   File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 722, in forward
[rank0]:     return self.text_model(
[rank0]:   File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 643, in forward
[rank0]:     encoder_outputs = self.encoder(
[rank0]:   File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 574, in forward
[rank0]:     layer_outputs = encoder_layer(
[rank0]:   File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 317, in forward
[rank0]:     hidden_states, attn_weights = self.self_attn(
[rank0]:   File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/yerong2/local/miniconda3/envs/instructdiff/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 257, in forward
[rank0]:     attn_output = torch.bmm(attn_probs, value_states)
[rank0]: RuntimeError: expected scalar type Half but found Float
```

And the configuration file is this 

```
# File modified by authors of InstructDiffusion from original (https://github.com/CompVis/stable-diffusion).
# See more details in LICENSE.

model:
  base_learning_rate: 1.0e-04
  weight_decay: 0.01
  target: ldm.models.diffusion.ddpm_edit.LatentDiffusion
  params:
    fp16: True
    deepspeed: 'deepspeed_1'
    ckpt_path: stable_diffusion/models/ldm/stable-diffusion-v1/v1-5-pruned-emaonly-adaption-task.ckpt
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: edited
    cond_stage_key: edit
    image_size: 32
    channels: 4
    cond_stage_trainable: false   # Note: different from the one we trained before
    conditioning_key: hybrid
    monitor: val/loss_simple_ema
    scale_factor: 0.18215

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 0 ]
        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32 # unused
        in_channels: 8
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False
        force_type_convert: True

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 64
    num_workers: 4
    train: 
      - ds1:
        target: dataset.editing.edit_zip_dataset.GIERDataset
        params:
          path: data/GIER_editing_data/
          split: train
          min_resize_res: 256
          max_resize_res: 256
          crop_res: 256
          flip_prob: 0.0
          zip_start_index: 0
          zip_end_index: 100
          sample_weight: 2.0

    validation:
      target: dataset.pose.pose.COCODataset
      params:
        root: data/coco/
        image_set: val2017
        is_train: False
        max_prompt_num: 5
        min_prompt_num: 1
        radius: 10
trainer:
  initial_scale: 13
  max_epochs: 200
  save_freq: 5
  accumulate_grad_batches: 1
  clip_grad: 0.0
  optimizer: adamw
```
